# Generated by Django 5.1.7 on 2026-03-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chat_messages",
            "0002_message_file_message_file_name_message_file_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="file_type",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
