# Generated by Django 5.1.7 on 2026-03-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_message", "New Message"),
                    ("quiz_completed", "Quiz Completed"),
                    ("meeting_asap", "Meeting ASAP"),
                    ("test_schedule_asap", "Test Schedule ASAP"),
                ],
                max_length=30,
            ),
        ),
    ]
