# Generated by Django 5.1.14 on 2026-03-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facetofaceinterview',
            name='attended',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facetofaceinterview',
            name='selected',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
