# Generated by Django 5.1.14

from django.db import migrations, models


def set_auto_congrats_sent_for_existing(apps, schema_editor):
    """Avoid sending duplicate auto message to already selected+attended candidates."""
    FaceToFaceInterview = apps.get_model('interviewer', 'FaceToFaceInterview')
    FaceToFaceInterview.objects.filter(attended=True, selected=True).update(auto_congrats_sent=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0002_add_attended_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='facetofaceinterview',
            name='auto_congrats_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_auto_congrats_sent_for_existing, noop),
    ]
